Add stackblitz links and info to issue template
Shopify/hydrogen-ui pull request #72
Opened 2022-11-16 18:44 UTC by frehner

### Description

Closes #56

### Additional context

---

### Before submitting the PR, please make sure you do the following:

- [x] Read the [Contributing Guidelines](https://github.com/shopify/hydrogen-ui/blob/main/contributing.md)
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`)
- [ ] Update docs in this repository according to your change
- [ ] Run `yarn changeset add` if this PR cause a version bump based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/). If you have a breaking change, it will need to wait until the next major version release. Otherwise, use patch updates even for new features. Read [more about Hydrogen-UI's versioning.](https://github.com/shopify/hydrogen-ui/blob/main/readme.md#versioning)

2022-11-17 03:47 UTC, cartogram approved these changes

2022-11-17 03:47 UTC, cartogram commented on apps/nextjs/README.md
>  This is a [Next.js](https://nextjs.org/) project bootstrapped with [`create-next-app`](https://github.com/vercel/next.js/tree/canary/packages/create-next-app).
Should we update the text of the rest of this readme?

2022-11-17 03:47 UTC, cartogram commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Please use our NextJS issue template here: [![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/fork/github/shopify/hydrogen-ui/tree/main/apps/n
```suggestion
Please use our NextJS stackblitz template to create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Get started by clicking the button below:
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/fork/github/shopify/hydrogen-ui/tree/main/apps/nextjs?file=pages%2Findex.tsx)
```

2022-11-17 18:49 UTC, cartogram commented on apps/nextjs/README.md
>  This is a [Next.js](https://nextjs.org/) project bootstrapped with [`create-next-app`](https://github.com/vercel/next.js/tree/canary/packages/create-next-app).
I'm not sure. I think leave it for now and maybe we revisit when there are multiple apps. @gfscott do you have any opinion on the content of this readme?

2022-11-18 17:10 UTC, elisenyang requested changes

2022-11-18 17:10 UTC, elisenyang commented on .github/ISSUE_TEMPLATE/bug_report.md
> +
What do you think about switching the order around like this?

**To Reproduce**
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error

If you're using Hydrogen UI with NextJS, you can use our template to create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Get started by clicking the button below:
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/fork/github/shopify/hydrogen-ui/tree/main/apps/nextjs?file=pages%2Findex.tsx)

2022-11-18 18:16 UTC, merged